-- 119. Create a sequence with START WITH, INCREMENT, MINVALUE and MAXVALUE

CREATE SEQUENCE IF NOT EXISTS test_seq3
INCREMENT 50
MINVALUE 400
MAXVALUE 6000
START WITH 500

SELECT nextval('test_seq3')